### ISSUE TITLE
get_data() cannot downloaded some measures listed in list_measures()

### ISSUE THREAD

**Issue by xywu-soc** [CDCgov/EPHTrackR#21]
**Describe the bug**
Cannot access some measures in the list from list_measures().

**Impact**
Selected measures seemingly available but cannot be accessed/downloaded regardless of how I modified the request.

**To Reproduce**
Steps to reproduce the behavior: Taking measure 1294 as an example. Same happened for many other measures I've tried but cannot recall now.
1. data_obj = get_data(measure = 1294, geo_type = 'County',  simplified_output = F, token = my_ephtn_token)
2. See error messages in the screenshot.

**Expected behavior**
The indicated measures should be downloadable, as they're in the list of measures from list_measures().

**Screenshots**
![Screenshot 2024-02-06 at 2 17 09 PM](https://github.com/CDCgov/EPHTrackR/assets/22750138/fd879128-bf0c-4854-bbde-7dbe0107cb2d)
![Screenshot 2024-02-06 at 2 17 59 PM](https://github.com/CDCgov/EPHTrackR/assets/22750138/4436b72b-506f-4b25-9831-806e9165f9b6)
![Screenshot 2024-02-06 at 2 18 55 PM](https://github.com/CDCgov/EPHTrackR/assets/22750138/8b01af5a-826b-4447-b8dd-eeca9f34731b)

**Logs**
Other error messages when trying to access measure 358. See below:
![Screenshot 2024-02-06 at 2 48 41 PM](https://github.com/CDCgov/EPHTrackR/assets/22750138/05f2e1b4-5db8-4b65-beaf-ae12558592d2)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma,
 - Browser: safari (non-relevant, because I'm using Rstudio 2023.06.1 with R 4.3.1)
 - Version: 14.2.1

**Additional context**
I'm using EPHTrackR package that newly installed, with API token. 
Rstudio version: 2023.06.1
R version: 4.3.1

**Comment by xywu-soc** [comment]
Getting the following error messages in R when trying to download measure 358:

> heat <- get_data(measure = 358, geo_type = 'County', temporalItems = 2000:2020,
+                  # strat_level = 'State x County',
+                  simplified_output = F, token = ephtn_token)
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^

**Comment by nskaff** [comment]
Hi, for measure 1294 the issue seems to be that the API is returning stratification levels that do not exist. This is something that needs to be address on our end, but in the meantime you could try specifying get_data("1294", strat_level = "ST_CT_IC_G", token=token)

**Comment by nskaff** [comment]
For measure 358, your request includes a lot of data and it might be getting throttled. The measure is daily and you've requested a large number of years and all counties. You may want to try subsetting by geo items or fewer temporal items. I'll also investigate to see if I can replicate the issue.

**Comment by xywu-soc** [comment]
> Hi, for measure 1294 the issue seems to be that the API is returning stratification levels that do not exist. This is something that needs to be address on our end, but in the meantime you could try specifying get_data("1294", strat_level = "ST_CT_IC_G", token=token)

Thank you so much for looking into this and the suggestion! Will try.

**Comment by xywu-soc** [comment]
> For measure 358, your request includes a lot of data and it might be getting throttled. The measure is daily and you've requested a large number of years and all counties. You may want to try subsetting by geo items or fewer temporal items. I'll also investigate to see if I can replicate the issue.

Subsetting by geo items or temporal items is a great idea. I've tried by geo items and it works well. Many thanks!!

**Comment by nskaff** [comment]
Specific issue with M1294 has been resolved by removing orphaned stratification levels from production data systems. Additional measures with similar issue will be addressed by mid-2024.

**Comment by xywu-soc** [comment]
> Specific issue with M1294 has been resolved by removing orphaned stratification levels from production data systems. Additional measures with similar issue will be addressed by mid-2024.

Thank you so much for the update and those potential updates! I was interrupted by some GitHub login issues and not able to reply to this note immediately.

**Comment by xywu-soc** [comment]
Hi, I'm continuing my work on the climate data from this platform, after some other tasks. I tried to download to the following measures after checking their temporal, geographic, and stratification level availability, but still cannot download it successfully.

The non-downloadable measures are: 1294 (the one you fixed last time), 1139, 1140, 1141

I tried with reduced geographic items and temporal items as well on M1294, but still doesn't work. Do you have any idea whether the issue comes from my code or the API? Many thanks!

My code:
tnd <- get_data(measure = 1294, geo_type = 'County', strat_level = 'ST_CT_IC_G',
                temporalItems = 2020, geoItems = 1001,
                simplified_output = F, token = ephtn_token)

Error message:
Building API call for measure: 1294 with stratification: State x County x Intensity Category Groups.
Error in ms_df[[7]][[k]]$localId : 
  $ operator is invalid for atomic vectors
